FROM almalinux:8

# install some necessary dependencies
RUN dnf -y install redhat-lsb && \
    dnf -y groupinstall 'Development Tools' && \
    dnf -y install java-1.8.0-openjdk ruby git maven cpan wget perl-IPC-Cmd rsync && \
    dnf config-manager --set-enabled powertools && \
    dnf -y module enable javapackages-tools && \
    dnf -y install ant-junit 

WORKDIR /home/git/zm-build

# volume to retrieve builds
VOLUME /home/git/zm-build/BUILDS

# copy build script
COPY build.sh /home/git/zm-build/
RUN chmod +x /home/git/zm-build/build.sh

# copy patch almalinux8
COPY zimbra-alma.patch /home/git/zm-build/

# build zimbra
ENTRYPOINT ["./build.sh"]
